#!/usr/bin/env python3
"""Send a markdown report as an HTML email via Gmail SMTP.

Usage:
    python3 send_mail.py <path/to/report.md>

Reads SMTP credentials from ~/.config/ai-infra-agent/mail.env:
    SMTP_HOST=smtp.gmail.com
    SMTP_PORT=465
    SMTP_USER=yourname@gmail.com
    SMTP_PASS=xxxxxxxxxxxxxxxx       # Gmail app password (16 chars, no spaces)
    MAIL_TO=recipient@example.com
    MAIL_FROM=optional-display <yourname@gmail.com>   # defaults to SMTP_USER
"""

from __future__ import annotations

import os
import re
import smtplib
import ssl
import sys
from email.message import EmailMessage
from email.utils import formatdate, make_msgid
from pathlib import Path


ENV_PATH = Path.home() / ".config" / "ai-infra-agent" / "mail.env"


def load_env(path: Path) -> dict[str, str]:
    if not path.is_file():
        sys.exit(f"MAIL FAILED: env file not found at {path}")
    env: dict[str, str] = {}
    for raw in path.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        k, v = line.split("=", 1)
        env[k.strip()] = v.strip().strip('"').strip("'")
    required = ["SMTP_USER", "SMTP_PASS", "MAIL_TO"]
    missing = [k for k in required if not env.get(k)]
    if missing:
        sys.exit(f"MAIL FAILED: missing keys {missing} in {path}")
    env.setdefault("SMTP_HOST", "smtp.gmail.com")
    env.setdefault("SMTP_PORT", "465")
    env.setdefault("MAIL_FROM", env["SMTP_USER"])
    return env


def md_to_html(md: str) -> str:
    """Convert the daily-report markdown to simple HTML (no external deps)."""
    lines = md.splitlines()
    out: list[str] = []
    in_list = False
    for line in lines:
        stripped = line.rstrip()
        if not stripped:
            if in_list:
                out.append("</ul>")
                in_list = False
            out.append("<br/>")
            continue
        # section headers: lines starting with emoji + space
        if re.match(r"^[📋🔧📄📰💬⭐]", stripped):
            if in_list:
                out.append("</ul>")
                in_list = False
            out.append(f'<h2 style="color:#0b5394;">{escape_html(stripped)}</h2>')
            continue
        # sub-headers (repository names, no bullet)
        if re.match(r"^[A-Za-z].*\(.+\)$", stripped) and not stripped.startswith("● "):
            if in_list:
                out.append("</ul>")
                in_list = False
            out.append(f'<h3 style="color:#3d85c6;margin-top:16px;">{escape_html(stripped)}</h3>')
            continue
        # mini-sub-headers (分类行，如 "MoE / Expert Parallelism")
        if not stripped.startswith("● ") and not stripped.startswith("http") and "●" not in stripped and not stripped.startswith(" "):
            if re.match(r"^[A-Za-z\u4e00-\u9fff].*", stripped):
                if in_list:
                    out.append("</ul>")
                    in_list = False
                out.append(f'<h4 style="color:#555;margin-top:10px;">{escape_html(stripped)}</h4>')
                continue
        # bullet lines
        if stripped.startswith("● "):
            if not in_list:
                out.append('<ul style="margin:4px 0 4px 20px;">')
                in_list = True
            out.append(f"<li>{linkify(escape_html(stripped[2:]))}</li>")
            continue
        # numbered highlights
        if re.match(r"^\d+\)", stripped):
            if in_list:
                out.append("</ul>")
                in_list = False
            out.append(f'<p><b>{linkify(escape_html(stripped))}</b></p>')
            continue
        # indented continuation
        if in_list and stripped.startswith("  "):
            out[-1] = out[-1].rstrip("</li>") + f"<br/><span style=\"color:#666;\">{linkify(escape_html(stripped.strip()))}</span></li>"
            continue
        # fallback paragraph
        if in_list:
            out.append("</ul>")
            in_list = False
        out.append(f"<p>{linkify(escape_html(stripped))}</p>")
    if in_list:
        out.append("</ul>")
    body = "\n".join(out)
    return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"></head>
<body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;line-height:1.55;color:#222;max-width:820px;margin:0 auto;padding:16px;">
{body}
<hr style="margin-top:32px;border:none;border-top:1px solid #ddd;"/>
<p style="color:#999;font-size:12px;">🤖 Generated by personal-agents/daily-ai-infra · 数据来源：GitHub、arXiv、HuggingFace、Interconnects、Reddit</p>
</body></html>
"""


def escape_html(s: str) -> str:
    return (s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))


def linkify(s: str) -> str:
    return re.sub(
        r"(https?://[^\s<>\"']+)",
        r'<a href="\1" style="color:#1155cc;">\1</a>',
        s,
    )


def send(report_path: Path, env: dict[str, str]) -> None:
    md = report_path.read_text(encoding="utf-8")
    # first non-empty line (without leading emoji) → subject
    subject = "AI 推理优化日报"
    for line in md.splitlines():
        s = line.strip()
        if s:
            subject = s
            break

    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"] = env["MAIL_FROM"]
    msg["To"] = env["MAIL_TO"]
    msg["Date"] = formatdate(localtime=True)
    msg["Message-ID"] = make_msgid()
    msg.set_content(md)  # plaintext fallback
    msg.add_alternative(md_to_html(md), subtype="html")

    host = env["SMTP_HOST"]
    port = int(env["SMTP_PORT"])
    ctx = ssl.create_default_context()
    try:
        if port == 465:
            with smtplib.SMTP_SSL(host, port, context=ctx, timeout=30) as s:
                s.login(env["SMTP_USER"], env["SMTP_PASS"])
                s.send_message(msg)
        else:
            with smtplib.SMTP(host, port, timeout=30) as s:
                s.ehlo()
                s.starttls(context=ctx)
                s.login(env["SMTP_USER"], env["SMTP_PASS"])
                s.send_message(msg)
    except Exception as e:
        sys.exit(f"MAIL FAILED: {e}")

    print(f"MAIL SENT → {env['MAIL_TO']} (subject: {subject})")


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit("Usage: send_mail.py <report.md>")
    path = Path(sys.argv[1]).expanduser()
    if not path.is_file():
        sys.exit(f"MAIL FAILED: report not found: {path}")
    env = load_env(Path(os.environ.get("MAIL_ENV_PATH", ENV_PATH)).expanduser())
    send(path, env)


if __name__ == "__main__":
    main()
